apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    limits.cpu: {{ .Values.resources.limits.cpu -}} m
    limits.memory: {{ .Values.resources.limits.memory -}} Gi
    requests.cpu: {{ .Values.resources.requests.cpu -}} m
    requests.memory: {{ .Values.resources.requests.memory -}} Gi
    requests.storage: {{ .Values.resources.requests.storage -}} Gi
