apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - default:
      memory: {{ div .Values.resources.limits.memory 4 -}} Mi
      cpu: {{ div .Values.resources.limits.cpu 4 -}} m
    defaultRequest:
      memory: {{ div .Values.resources.limits.memory 4 -}} Mi
      cpu: {{ div .Values.resources.limits.cpu 4 -}} m
    type: Container
