apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flusso-in-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo-workflows
