apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flusso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-edit
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo-workflows
